console.log('first example');
var str = ' test,yantra ';
console.log('to upper case',str.toUpperCase());
var str1 = 'TESTYANTRA';
console.log('length of the string1',str.length);
console.log('to lower case',str1.toLowerCase());
console.log('char at position 2',str.charAt(2));
console.log('index of Yantra',str.indexOf('yantra',2));
console.log('concating',str.concat('company'));
console.log('a is present in string',str1.includes('A'))
console.log('after replacing',str1.replace('YANTRA','yantra'));
console.log('search yantra',str1.search('YANTRA'));
console.log('after trimming',str.trim());
console.log('substring of string1 from 1 to 3',str1.substr(0,3));
console.log('after splitting',str1.split(","));
console.log('******************************************************');
console.log('second example');
var str = ' tecnotree ';
console.log('to upper case',str.toUpperCase());
var str1 = 'TECNOTREE';
console.log('length of the string1',str.length);
console.log('to lower case',str1.toLowerCase());
console.log('char at position 7',str.charAt(7));
console.log('index of tree',str.indexOf('TREE',2));
console.log('concating',str.concat('company'));
console.log('A is present in string',str1.includes('A'))
console.log('after replacing',str1.replace('TREE','tree'));
console.log('search TREE',str1.search('TREE'));
console.log('after trimming',str.trim());
console.log('substring of string1 from 1 to 3',str1.substr(0,3));
console.log('after splitting',str1.split(','));
console.log('******************************************************');
console.log('third example');
var str = ' karnataka ';
console.log('to upper case',str.toUpperCase());
var str1 = 'KARNATAKA';
console.log('length of the string1',str.length);
console.log('to lower case',str1.toLowerCase());
console.log('char at position 8',str.charAt(8));
console.log('index of nataka',str.indexOf('NATAKA',2));
console.log('concating',str.concat(' STATE'));
console.log('T is present in string',str1.includes('T'))
console.log('after replacing',str1.replace('NATAKA','nataka'));
console.log('search state',str1.search('state'));
console.log('after trimming',str.trim());
console.log('substring of string1 from 1 to 3',str1.substr(0,3));
console.log('after splitting',str1.split(','));
console.log('******************************************************');
console.log('fourth example');
var str = ' apple ';
console.log('to upper case',str.toUpperCase());
var str1 = 'APPLE';
console.log('length of the string1',str.length);
console.log('to lower case',str1.toLowerCase());
console.log('char at position 4',str.charAt(4));
console.log('index of LE',str.indexOf('LE',2));
console.log('concating',str.concat('FRUIT'));
console.log('P is present in string',str1.includes('P'))
console.log('after replacing',str1.replace('apple','orange'));
console.log('search Fruit',str1.search('FRUIT'));
console.log('after trimming',str.trim());
console.log('substring of string1 from 1 to 3',str1.substr(0,3));
console.log('after splitting',str1.split(','));
console.log('******************************************************');
console.log('fifth example');
var str = ' yamaha ';
console.log('to upper case',str.toUpperCase());
var str1 = 'YAMAHA';
console.log('length of the string1',str.length);
console.log('to lower case',str1.toLowerCase());
console.log('char at position 6',str.charAt(6));
console.log('index of maha',str.indexOf('MAHA',2));
console.log('concating',str.concat('BIKE'));
console.log('M is present in string',str1.includes('M'))
console.log('after replacing',str1.replace('yamaha','KTM'));
console.log('search Bike',str1.search('bike'));
console.log('after trimming',str.trim());
console.log('substring of string1 from 1 to 3',str1.substr(0,3));
console.log('after splitting',str1.split(','));
console.log('******************************************************');
console.log('sixth example');
var str = ' dell ';
console.log('to upper case',str.toUpperCase());
var str1 = 'DELL';
console.log('length of the string1',str.length);
console.log('to lower case',str1.toLowerCase());
console.log('char at position 3',str.charAt(3));
console.log('index of ',str.indexOf('ELL',2));
console.log('concating',str.concat(' LAPTOP'));
console.log('E is present in string',str1.includes('E'))
console.log('after replacing',str1.replace('dell','HP'));
console.log('search HP',str1.search('HP'));
console.log('after trimming',str.trim());
console.log('substring of string1 from 1 to 3',str1.substr(0,3));
console.log('after splitting',str1.split(','));
console.log('******************************************************');
console.log('seventh example');
var str = ' samsung ';
console.log('to upper case',str.toUpperCase());
var str1 = 'SAMSUNG';
console.log('length of the string1',str.length);
console.log('to lower case',str1.toLowerCase());
console.log('char at position 5',str.charAt(5));
console.log('index of SUNG',str.indexOf('SUNG',2));
console.log('concating',str.concat(' MOBILE'));
console.log('s is present in string',str1.includes('S'))
console.log('after replacing',str1.replace('samsung','REDMI'));
console.log('search MOBILE',str1.search('REDMI'));
console.log('after trimming',str.trim());
console.log('substring of string1 from 1 to 3',str1.substr(0,3));
console.log('after splitting',str1.split(','));
console.log('******************************************************');
console.log('eighth example');
var str = ' honey ';
console.log('to upper case',str.toUpperCase());
var str1 = 'HONEY';
console.log('length of the string1',str.length);
console.log('to lower case',str1.toLowerCase());
console.log('char at position 2',str.charAt(2));
console.log('index of Y',str.indexOf('Y',2));
console.log('concating',str.concat(' CAKE'));
console.log('H is present in string',str1.includes('h'))
console.log('after replacing',str1.replace('honey','CHOCOLATE'));
console.log('search LATE',str1.search('LATE'));
console.log('after trimming',str.trim());
console.log('substring of string1 from 1 to 3',str1.substr(0,3));
console.log('after splitting',str1.split(','));
console.log('******************************************************');
console.log('ninth example');
var str = ' titan ';
console.log('to upper case',str.toUpperCase());
var str1 = 'TITAN';
console.log('length of the string1',str.length);
console.log('to lower case',str1.toLowerCase());
console.log('char at position 4',str.charAt(4));
console.log('index of TAN',str.indexOf('TAN',1));
console.log('concating',str.concat('WATCH'));
console.log('W is present in string',str1.includes('W'))
console.log('after replacing',str1.replace('titan','CASIO'));
console.log('search CASIO',str1.search('CASIO'));
console.log('after trimming',str.trim());
console.log('substring of string1 from 1 to 3',str1.substr(0,3));
console.log('after splitting',str1.split(','));
console.log('******************************************************');
console.log('tenth example');
var str = ' bangluru ';
console.log('to upper case',str.toUpperCase());
var str1 = 'BANGLURU';
console.log('length of the string1',str.length);
console.log('to lower case',str1.toLowerCase());
console.log('char at position 3',str.charAt(3));
console.log('index of LURU',str.indexOf('LURU',2));
console.log('concating',str.concat('CAPITAL CITY'));
console.log('C is present in string',str1.includes('C'))
console.log('after replacing',str1.replace('bengluru','MUMBAI'));
console.log('search BAI',str1.search('BAI'));
console.log('after trimming',str.trim());
console.log('substring of string1 from 1 to 3',str1.substr(0,3));
console.log('after splitting',str1.split(','));
